image: ubuntu:latest

stages:
  - build

build:
  stage: build
  timeout: 4 hours
  before_script:
    - apt-get -qq update
    - DEBIAN_FRONTEND=noninteractive TZ=Europe/Berlin apt-get -qq install -y build-essential cmake device-tree-compiler git ctags python
  script:
    - make setup
    - make apps
    - gzip apps/build/arm-rtems6-beagleboneblack/wifi-sample/wifi-sample-sd-image.img
  artifacts:
    name: wifi-sample-$CI_COMMIT_SHA
    paths:
      - apps/build/arm-rtems6-beagleboneblack/wifi-sample/wifi-sample-sd-image.img.gz
    expire_in: 1 days
