import rtems_waf.rtems as rtems
import rtems_waf.rtems_bsd as rtems_bsd
import os

def build(bld):
    rtems.build(bld)
    bld(features = 'c cprogram',
        target = 'fb-sample.exe',
        source = ['init.c'],
        lib = ['m', 'lvgl', 'bsd'])
    bld(rule = "create-sdcardimage.sh ${SRC} ${TGT}",
        source = "fb-sample.exe",
        target = "fb-sample-sd-image.img")
